### ISSUE TITLE
Document and simplify set up of database population code

### ISSUE THREAD

**Issue by talnor** [genomic-medicine-sweden/docker-sc2reporter#13]
## Description

The scripts currently used for populating the mongodb can be found [here](https://github.com/genomic-medicine-sweden/sc2reporter/tree/master/scripts) and are written in perl.

For easier use it would be good to document the installation procedure for all requirements and set this up in conda environments or docker containers.

## This can be closed when

- [x] Documented installation for the database population scripts
- [x] Set up installation in conda or docker for portability and easy installation for new users

**Comment by Fattigman** [comment]
Done!
