### ISSUE TITLE
Sample list page

### ISSUE THREAD

**Issue by elevu** [genomic-medicine-sweden/docker-sc2reporter#25]
http://34.125.180.44/docs#/Samples/read_samples_samples__get

**Comment by moedarrah** [comment]
![Screen Shot 2022-09-02 at 10 05 10](https://user-images.githubusercontent.com/41540288/188089898-39e6afd0-d6c0-4eb6-896d-d1fd6bd7625e.png)

**Comment by elevu** [comment]
done
