### ISSUE TITLE
Pangolin report graph

### ISSUE THREAD

**Issue by elevu** [genomic-medicine-sweden/docker-sc2reporter#27]

**Comment by moedarrah** [comment]
![Screen Shot 2022-09-02 at 10 09 27](https://user-images.githubusercontent.com/41540288/188093074-877d75d4-032d-48e8-bc36-adb671357df5.png)

**Comment by Fattigman** [comment]
I added a /samples/pangolin/ endpoint which will fetch all samples with the queried pangolin type.

**Comment by Fattigman** [comment]
Corrected: /samples/pango/ is the endpoint

**Comment by moedarrah** [comment]
https://34.125.180.44/docs#/Samples/get_samples_with_pangotype_samples_pango__get

**Comment by Fattigman** [comment]
Issue is blocked.  Back-end need to provide the data to be plotted.
My plan is for the endpoint to return:
{
  samples : [sample1, sample2,....],
  plotData : [ {x1:xval, y1:yval} ,{x2:xval, y2:yval }]
}

**Comment by moedarrah** [comment]
Done!
