### ISSUE TITLE
Nextrain page report

### ISSUE THREAD

**Issue by elevu** [genomic-medicine-sweden/docker-sc2reporter#28]

**Comment by moedarrah** [comment]
![Screen Shot 2022-09-02 at 10 09 54](https://user-images.githubusercontent.com/41540288/188093300-737a47bf-7b3f-4a56-8071-4cc2125cab00.png)

**Comment by Fattigman** [comment]
I added a /samples/nextclade/ endpoint which will fetch all samples with the queried nextclade type.

**Comment by moedarrah** [comment]
https://34.125.180.44/docs#/Samples/get_samples_with_nextclade_samples_nextclade__get

**Comment by elevu** [comment]
done

**Comment by Fattigman** [comment]
Issue reopened to add plot of nextclade spread.
Issue is blocked. Back-end need to provide the data to be plotted.
My plan is for the endpoint to return:
{
samples : [sample1, sample2,....],
plotData : [ {x1:xval, y1:yval} ,{x2:xval, y2:yval }]
}
