### ISSUE TITLE
Report for selected samples

### ISSUE THREAD

**Issue by elevu** [genomic-medicine-sweden/docker-sc2reporter#30]

**Comment by moedarrah** [comment]
![Screen Shot 2022-09-02 at 10 11 02](https://user-images.githubusercontent.com/41540288/188094248-a03ec884-e8d9-4f48-b892-a96b7e8a9f43.png)

**Comment by Fattigman** [comment]
This feature has been in the backend for 8 months now.
It's the /samples/multiple/ endpoint.

**Comment by Fattigman** [comment]
Or do you want it in another format?

**Comment by talnor** [comment]
This looks like it is done @Fattigman? Closing it.
