### ISSUE TITLE
Sc2report dashboard

### ISSUE THREAD

**Issue by Fattigman** [genomic-medicine-sweden/docker-sc2reporter#48]
![Screenshot 2022-10-06 at 10 16 57](https://user-images.githubusercontent.com/32386766/194259629-21646706-9cdd-45a2-85b2-18a91f8ccf50.png)

## The dashboard will consist of three components: 

1. Table with general stats for all the isolate runs.
2. Plot of pangolin distribution over time, goes from 0-100% on one y-scale and number of samples on other y scale. Time for the x-scale
3. Table of pangolin type assignemnts per week.

First step would be to create a /dashboard endpoint with the relevant data.

**Comment by Fattigman** [comment]
Endpoint can be found here:
https://34.125.210.143/docs#/Dashboard/get_dashboard_dashboard__get

A thought is that we ditch the pangolin table, since it is already implied by the plot.

**Comment by moedarrah** [comment]
Can you sort the dashboard_data array according to the date? and I noticed some dates with a day 0 @Fattigman 

<img width="501" alt="Screen Shot 2022-10-21 at 15 33 02" src="https://user-images.githubusercontent.com/41540288/197208216-0da9a461-f1d8-4bd9-85d7-7959c3ad5396.png">

**Comment by Fattigman** [comment]
I can sort the data. 
Also it's not day, it's week as in year-month-week.

**Comment by moedarrah** [comment]
Done! missing feature is added as a separate issue
